# Generated by Django 5.2.4 on 2025-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMSapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_Owner",
            new_name="is_owner",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_transport",
            new_name="is_transporter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Company_Name",
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
