# Generated by Django 5.2.4 on 2025-07-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMSapp", "0003_offer_receiver_alter_offer_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat_message",
            old_name="timestap",
            new_name="timestamp",
        ),
    ]
