# Generated by Django 5.2.4 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0006_vehicle_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='truck_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
