# Generated by Django 5.2.4 on 2025-08-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0007_vehicle_truck_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='TMSapp.vehicle'),
        ),
    ]
