# Generated by Django 5.2.4 on 2025-08-25 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0008_alter_staff_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
