# Generated by Django 5.2.4 on 2025-08-26 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0010_rename_time_stamp_offer_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='receiver',
        ),
        migrations.AddField(
            model_name='offer',
            name='changed_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
