# Generated by Django 5.2.4 on 2025-09-01 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0012_offer_receiver_offer_updated_at_alter_offer_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='TMSapp.package'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='transporter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
