# Generated by Django 5.2.4 on 2025-09-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0013_invoice_transporter_alter_invoice_issue_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='package',
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rooms', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='TMSapp.package')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('package', 'owner', 'transporter')},
            },
        ),
        migrations.AddField(
            model_name='chat_message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='TMSapp.chatroom'),
        ),
    ]
