# Generated by Django 5.2.4 on 2025-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0014_remove_chat_message_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Negotiating', 'Negotiating'), ('Booked', 'Booked'), ('Loaded', 'Loaded'), ('Delivered', 'Delivered')], default='Available', max_length=20),
        ),
    ]
