# Generated by Django 5.2.6 on 2025-10-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0015_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reopened_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_offers', to='TMSapp.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_by_owner', 'Accepted by Owner'), ('confirmed_by_transporter', 'Confirmed by Transporter'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reopened', 'Reopened'), ('locked', 'Locked')], default='pending', max_length=30),
        ),
    ]
